#index:
#    path: /
#    controller: App\Controller\DefaultController::index

kraken_list:
    path: /kraken
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\KrakenController::addOrDeleteKraken